In [2]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 4.4 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [3]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [4]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']
#Load Datasets
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals]=df[cols_with_missing_vals].replace(0,np.nan)

#Imputing these nan values with mean of the respective column
df.fillna(df.mean(),inplace=True)

print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [7]:

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

# using bayesian optimizer

In [11]:
# Creating a study object and optimize the objective function
study=optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler()) # We aim to maximize accuracy
study.optimize(objective , n_trials=75)

[I 2026-06-22 07:56:54,011] A new study created in memory with name: no-name-4ad7a955-09cb-4a2d-a893-03e3469d1974
[I 2026-06-22 07:56:54,630] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 99, 'max_depth': 20}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:56:55,728] Trial 1 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 196, 'max_depth': 6}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:56:56,151] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 76, 'max_depth': 5}. Best is trial 2 with value: 0.7709497206703911.
[I 2026-06-22 07:56:56,749] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 100, 'max_depth': 8}. Best is trial 2 with value: 0.7709497206703911.
[I 2026-06-22 07:56:57,756] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 170, 'max_depth': 13}. Best is trial 2 with value: 0.7709497206703911.
[I 2026-06-22 07:56:58,689] Trial 5 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 160, 'max_depth': 9}. Best is trial 2 with value: 0.7709497206703911.
[I 2026-06-22 07:56:59,696] Trial 6 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 187, 'max_depth': 5}. Best is trial 2 with value: 0.7709497206703911.
[I 2026-06-22 07:56:59,998] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 17}. Best is trial 7 with value: 0.7728119180633147.
[I 2026-06-22 07:57:00,581] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 106, 'max_depth': 5}. Best is trial 7 with value: 0.7728119180633147.
[I 2026-06-22 07:57:01,422] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 140, 'max_depth': 13}. Best is trial 7 with value: 0.7728119180633147.
[I 2026-06-22 07:57:01,802] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 20}. Best is trial 7 with value: 0.7728119180633147.
[I 2026-06-22 07:57:02,329] Trial 11 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 52, 'max_depth': 15}. Best is trial 7 with value: 0.7728119180633147.
[I 2026-06-22 07:57:03,071] Trial 12 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 17}. Best is trial 12 with value: 0.7783985102420857.
[I 2026-06-22 07:57:03,821] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 76, 'max_depth': 17}. Best is trial 12 with value: 0.7783985102420857.
[I 2026-06-22 07:57:04,665] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 17}. Best is trial 12 with value: 0.7783985102420857.
[I 2026-06-22 07:57:05,492] Trial 15 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 17}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:06,274] Trial 16 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 131, 'max_depth': 12}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:07,048] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 130, 'max_depth': 11}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:07,837] Trial 18 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 131, 'max_depth': 12}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:08,583] Trial 19 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 116, 'max_depth': 15}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:09,368] Trial 20 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 152, 'max_depth': 3}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:10,110] Trial 21 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 126, 'max_depth': 11}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:10,973] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 142, 'max_depth': 11}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:11,695] Trial 23 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 116, 'max_depth': 13}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:12,537] Trial 24 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 139, 'max_depth': 9}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:13,733] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 158, 'max_depth': 15}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:14,733] Trial 26 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 19}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:16,311] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 170, 'max_depth': 12}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:17,228] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 90, 'max_depth': 14}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:18,124] Trial 29 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 108, 'max_depth': 9}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:18,950] Trial 30 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 19}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:19,493] Trial 31 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 89, 'max_depth': 18}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:20,392] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 149, 'max_depth': 16}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:20,804] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 66, 'max_depth': 7}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:21,497] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 117, 'max_depth': 14}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:22,102] Trial 35 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:23,155] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 174, 'max_depth': 20}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:24,340] Trial 37 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 197, 'max_depth': 16}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:25,536] Trial 38 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 13}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:26,662] Trial 39 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 188, 'max_depth': 16}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:27,747] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 191, 'max_depth': 7}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:29,278] Trial 41 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 163, 'max_depth': 18}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:30,920] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 150, 'max_depth': 16}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:32,774] Trial 43 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 178, 'max_depth': 18}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:33,446] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 110, 'max_depth': 14}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:34,015] Trial 45 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 94, 'max_depth': 19}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:34,510] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 79, 'max_depth': 12}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:35,281] Trial 47 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 17}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:36,086] Trial 48 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 130, 'max_depth': 16}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:36,825] Trial 49 finished with value: 0.7728119180633146 and parameters: {'n_estimators': 122, 'max_depth': 12}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:37,643] Trial 50 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 134, 'max_depth': 15}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:38,530] Trial 51 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 17}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:38,949] Trial 52 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 17}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:39,626] Trial 53 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 111, 'max_depth': 18}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:40,699] Trial 54 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 179, 'max_depth': 14}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:41,925] Trial 55 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 146, 'max_depth': 10}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:43,526] Trial 56 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 164, 'max_depth': 19}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:44,490] Trial 57 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 126, 'max_depth': 15}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:45,424] Trial 58 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 154, 'max_depth': 17}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:45,767] Trial 59 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 55, 'max_depth': 10}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:46,229] Trial 60 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 86, 'max_depth': 3}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:46,848] Trial 61 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 19}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:47,581] Trial 62 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 121, 'max_depth': 20}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:48,319] Trial 63 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 121, 'max_depth': 20}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:49,017] Trial 64 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 20}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:49,772] Trial 65 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 18}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:50,571] Trial 66 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 20}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:51,345] Trial 67 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 127, 'max_depth': 13}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:52,193] Trial 68 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 140, 'max_depth': 19}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:52,870] Trial 69 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 20}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:53,688] Trial 70 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 136, 'max_depth': 11}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:54,674] Trial 71 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 121, 'max_depth': 18}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:55,852] Trial 72 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 121, 'max_depth': 16}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:57,110] Trial 73 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 130, 'max_depth': 18}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-06-22 07:57:57,758] Trial 74 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 20}. Best is trial 15 with value: 0.7802607076350093.

In [12]:
print(f"Best Trail accuracy : {study.best_trial.values}")
print(f"Best hyperparameter : {study.best_trial.params}")

Best Trail accuracy : [0.7802607076350093]
Best hyperparameter : {'n_estimators': 123, 'max_depth': 17}

In [13]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# Using Random Sample

In [16]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=75)  # Run 50 trials to find the best hyperparameters

[I 2026-06-22 07:16:47,965] A new study created in memory with name: no-name-40bab72f-532b-4267-94f0-58c50379e8e2
[I 2026-06-22 07:16:48,791] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 19}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:16:49,568] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 83, 'max_depth': 14}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:16:51,274] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 173, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:16:52,243] Trial 3 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 104, 'max_depth': 11}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:16:53,519] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 156, 'max_depth': 18}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-22 07:16:53,836] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 57, 'max_depth': 13}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-22 07:16:54,681] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 157, 'max_depth': 13}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-06-22 07:16:55,101] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 17}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:16:55,723] Trial 8 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 110, 'max_depth': 18}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:16:56,369] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 120, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:16:56,693] Trial 10 finished with value: 0.761638733705773 and parameters: {'n_estimators': 59, 'max_depth': 10}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:16:57,471] Trial 11 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 143, 'max_depth': 16}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:16:58,562] Trial 12 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 179, 'max_depth': 18}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:16:59,760] Trial 13 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 163, 'max_depth': 3}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:17:00,873] Trial 14 finished with value: 0.756052141527002 and parameters: {'n_estimators': 160, 'max_depth': 3}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:17:01,837] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 182, 'max_depth': 19}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:17:02,310] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 90, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:17:02,907] Trial 17 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 114, 'max_depth': 11}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-06-22 07:17:03,869] Trial 18 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 176, 'max_depth': 12}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:04,562] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 134, 'max_depth': 17}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:04,883] Trial 20 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 63, 'max_depth': 5}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:05,645] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 11}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:06,321] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 132, 'max_depth': 6}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:07,238] Trial 23 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 174, 'max_depth': 16}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:07,918] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 128, 'max_depth': 14}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:08,803] Trial 25 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 187, 'max_depth': 4}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:09,104] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 58, 'max_depth': 6}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:09,391] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 55, 'max_depth': 7}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:10,013] Trial 28 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 124, 'max_depth': 6}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:10,812] Trial 29 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 170, 'max_depth': 3}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:11,251] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 18}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:12,776] Trial 31 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 196, 'max_depth': 6}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:13,416] Trial 32 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 85, 'max_depth': 17}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:13,975] Trial 33 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 14}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:14,703] Trial 34 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 152, 'max_depth': 4}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:15,690] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 188, 'max_depth': 17}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:16,515] Trial 36 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 154, 'max_depth': 16}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:16,835] Trial 37 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 68, 'max_depth': 3}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:17,754] Trial 38 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 171, 'max_depth': 20}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:18,470] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 134, 'max_depth': 14}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:19,049] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 11}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:19,954] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 167, 'max_depth': 14}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:20,638] Trial 42 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 137, 'max_depth': 5}. Best is trial 18 with value: 0.7765363128491621.
[I 2026-06-22 07:17:21,065] Trial 43 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 80, 'max_depth': 12}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:21,621] Trial 44 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 115, 'max_depth': 4}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:21,907] Trial 45 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 61, 'max_depth': 3}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:22,345] Trial 46 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 6}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:22,721] Trial 47 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 66, 'max_depth': 12}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:22,966] Trial 48 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 50, 'max_depth': 4}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:24,174] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 168, 'max_depth': 13}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:24,989] Trial 50 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 97, 'max_depth': 20}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:26,099] Trial 51 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 150, 'max_depth': 7}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:26,612] Trial 52 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 107, 'max_depth': 4}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:27,021] Trial 53 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 5}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:27,914] Trial 54 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 19}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:28,794] Trial 55 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 161, 'max_depth': 13}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:29,297] Trial 56 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:29,759] Trial 57 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 84, 'max_depth': 19}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:30,112] Trial 58 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 68, 'max_depth': 4}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:31,091] Trial 59 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 184, 'max_depth': 15}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:31,561] Trial 60 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 87, 'max_depth': 9}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:32,323] Trial 61 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 145, 'max_depth': 8}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:33,326] Trial 62 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 181, 'max_depth': 14}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:34,283] Trial 63 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 177, 'max_depth': 14}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:35,045] Trial 64 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 148, 'max_depth': 6}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:36,163] Trial 65 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 12}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:37,338] Trial 66 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 161, 'max_depth': 3}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:37,844] Trial 67 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 60, 'max_depth': 9}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:38,782] Trial 68 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 134, 'max_depth': 9}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:39,357] Trial 69 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 102, 'max_depth': 13}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:40,395] Trial 70 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 192, 'max_depth': 19}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:40,691] Trial 71 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 53, 'max_depth': 10}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:41,099] Trial 72 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 75, 'max_depth': 9}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:42,115] Trial 73 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 188, 'max_depth': 19}. Best is trial 43 with value: 0.7783985102420856.
[I 2026-06-22 07:17:42,578] Trial 74 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 20}. Best is trial 43 with value: 0.7783985102420856.

In [17]:
print(f"Best Trail accuracy : {study.best_trial.values}")
print(f"Best hyperparameter : {study.best_trial.params}")

Best Trail accuracy : [0.7783985102420856]
Best hyperparameter : {'n_estimators': 80, 'max_depth': 12}

In [18]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

#Using GridSearch

In [19]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [20]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-06-22 07:19:49,715] A new study created in memory with name: no-name-dbfcbe87-db29-4148-90c8-818ad702527c
[I 2026-06-22 07:19:50,423] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:19:51,833] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-22 07:19:52,295] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:19:53,224] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:19:54,136] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:19:54,589] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:19:55,350] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:19:56,158] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:19:57,206] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:19:58,842] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:20:00,023] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:20:01,338] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:20:02,923] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-22 07:20:03,268] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-22 07:20:04,147] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-22 07:20:04,604] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [21]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [22]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# Optuna Visualization

In [23]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [33]:
# 1. Optimization History
plot_optimization_history(study).show()

In [34]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [35]:
# 3. Slice Plot
plot_slice(study).show()

In [36]:
# 4. Contour Plot
plot_contour(study).show()

In [37]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

# Define By Run (Dynamic Search Space)

In [14]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [15]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [16]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-06-22 08:03:04,638] A new study created in memory with name: no-name-0fe19fa9-d28f-49f9-b62f-2720ad72f0a0
[I 2026-06-22 08:03:04,703] Trial 0 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 1.4883856983490695, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-06-22 08:03:07,738] Trial 1 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 178, 'learning_rate': 0.031055377514805766, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-06-22 08:03:07,765] Trial 2 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14204820837153184, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:09,305] Trial 3 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 282, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:09,347] Trial 4 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.2675828004813915, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:10,775] Trial 5 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 274, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:14,386] Trial 6 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 150, 'learning_rate': 0.09201754021372564, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:17,131] Trial 7 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 213, 'learning_rate': 0.2811426621095874, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:19,178] Trial 8 finished with value: 0.7448789571694601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 91, 'learning_rate': 0.23776294763688088, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:20,495] Trial 9 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 83, 'learning_rate': 0.033308548468605585, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:20,841] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 78.37197194659767, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:21,154] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 63.660010982147824, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:21,550] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 84.92088632950984, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:21,602] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.616184810398101, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:21,635] Trial 14 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.10330398735840068, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:21,702] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.832913584025226, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:21,737] Trial 16 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8475652584759947, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:22,913] Trial 17 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 223, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:22,949] Trial 18 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.6039977050151202, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:22,996] Trial 19 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.10124112023703648, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,652] Trial 20 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 129, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,741] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 16.354254645906387, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,776] Trial 22 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.1572747065876174, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,807] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3308047411682166, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,839] Trial 24 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3613285937916541, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,871] Trial 25 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 0.2273801900680221, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,906] Trial 26 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9345188666681367, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:23,947] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.3445586225654313, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,235] Trial 28 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 54, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,277] Trial 29 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.49900932077703347, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,309] Trial 30 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.1877076402251853, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,418] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 22.462681652754345, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,587] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 34.743915344348416, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,616] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17182366056302176, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,646] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16863758856892813, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:24,692] Trial 35 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.15803234441253397, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:26,104] Trial 36 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 235, 'learning_rate': 0.011047595711711282, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:27,019] Trial 37 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 166, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:27,051] Trial 38 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5400600369467504, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:28,861] Trial 39 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 127, 'learning_rate': 0.010764469644082269, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:28,892] Trial 40 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.18885757881366638, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:28,922] Trial 41 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.32993576952649595, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:28,952] Trial 42 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13982058814203818, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:28,982] Trial 43 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13571636312665478, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:29,020] Trial 44 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.12831083388760367, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:29,050] Trial 45 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15624244762998798, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:33,444] Trial 46 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 255, 'learning_rate': 0.08268892883904745, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:33,490] Trial 47 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.26679554182945314, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,502] Trial 48 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 197, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,533] Trial 49 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10037957375041826, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,566] Trial 50 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21271351942489372, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,600] Trial 51 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16035501753787557, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,632] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14390891762570693, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,664] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.259295227515521, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,694] Trial 54 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14949806180420197, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:35,725] Trial 55 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12786784512419636, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:49,375] Trial 56 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 300, 'learning_rate': 0.028474500775840014, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:49,437] Trial 57 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.1158302283049379, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:49,488] Trial 58 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13386760565924663, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:49,564] Trial 59 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4233832453616478, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,306] Trial 60 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 53, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,375] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12772315311364382, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,433] Trial 62 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23780483155131296, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,467] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12958263246184692, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,509] Trial 64 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.1038731766132458, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,540] Trial 65 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3008067173481174, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,590] Trial 66 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.14151453905372574, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,622] Trial 67 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25616509378438396, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,654] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.20469752263048563, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,707] Trial 69 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10369108047095106, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,767] Trial 70 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 0.41748615611161777, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,822] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14044041945701496, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,876] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13349944230769126, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,932] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.20266559946299786, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:50,983] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12488023117411769, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:51,035] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19196190388313353, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:54,155] Trial 76 finished with value: 0.7541899441340781 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 101, 'learning_rate': 0.11504140157069354, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:56,279] Trial 77 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 190, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:56,340] Trial 78 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.32497879292801657, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:56,396] Trial 79 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7010784487466755, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:56,462] Trial 80 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13246775569554708, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 2 with value: 0.7895716945996275.
[I 2026-06-22 08:03:56,515] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14664238964313803, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7895716945996275.

In [17]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.14204820837153184, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [18]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.770950,2026-06-22 08:03:04.642155,2026-06-22 08:03:04.703637,0 days 00:00:00.061482,1.488386,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.765363,2026-06-22 08:03:04.705560,2026-06-22 08:03:07.738416,0 days 00:00:03.032856,NaN,NaN,GradientBoosting,NaN,NaN,0.031055,14.0,8.0,10.0,178.0,COMPLETE
2,2,0.789572,2026-06-22 08:03:07.739450,2026-06-22 08:03:07.765133,0 days 00:00:00.025683,0.142048,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.756052,2026-06-22 08:03:07.766114,2026-06-22 08:03:09.305776,0 days 00:00:01.539662,NaN,True,RandomForest,NaN,NaN,NaN,16.0,6.0,3.0,282.0,COMPLETE
4,4,0.769088,2026-06-22 08:03:09.307045,2026-06-22 08:03:09.347366,0 days 00:00:00.040321,0.267583,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.767225,2026-06-22 08:04:01.839957,2026-06-22 08:04:02.608043,0 days 00:00:00.768086,NaN,False,RandomForest,NaN,NaN,NaN,12.0,4.0,7.0,146.0,COMPLETE
96,96,0.716946,2026-06-22 08:04:02.609126,2026-06-22 08:04:02.643737,0 days 00:00:00.034611,0.221053,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.789572,2026-06-22 08:04:02.644754,2026-06-22 08:04:02.675615,0 days 00:00:00.030861,0.115754,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.787709,2026-06-22 08:04:02.676607,2026-06-22 08:04:02.708803,0 days 00:00:00.032196,0.101323,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.787709,2026-06-22 08:04:02.709785,2026-06-22 08:04:02.740945,0 days 00:00:00.031160,0.155937,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [19]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
GradientBoosting    11
RandomForest        10
Name: count, dtype: int64

In [20]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.749450
RandomForest        0.766108
SVM                 0.777880
Name: value, dtype: float64